[tools]
# Go version from your go.mod file
go = "1.25.5"

# Node.js for JavaScript/TypeScript
node = "24.13.0"
npm = "11.5.1"

# Pre-commit for Git hooks
pre-commit = "4.5.1"

# Additional tools for development
golangci-lint = "2.8.0"
"go:github.com/spechtlabs/golint-sl/cmd/golint-sl" = "latest"
goreleaser = "2.12.0"
kind = "0.31.0"
kubectl = "1.35.0"
markdownlint-cli2 = "0.20.0"

swag = "1.8.7"
"npm:npm-check-updates" = "latest"
protoc-gen-go = "latest"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "0.17.2"

[env]
# Set environment variables for Go development
GO111MODULE = "on"

# Vue.js related environment variables
NODE_ENV = "development"
