repos:
  - repo: local
    hooks:
      - id: make-generate
        name: Run 'make -C src generate'
        entry: make -C src generate
        language: system
        pass_filenames: false
        files: ^src/pkg/api/.*\.go$
        stages: [pre-commit]
  # Generic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest version from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ^src/pkg/swagger/
      - id: end-of-file-fixer
        exclude: ^src/pkg/swagger/
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        exclude: ^src/pkg/swagger/
      - id: check-added-large-files
        name: check for added large files
        description: Prevents giant files from being committed
        args: ['--maxkb=500']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0  # Use the latest version
    hooks:
      - id: gitleaks
